name: Build

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 15 * * *'
    
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write    

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Run script
        run: |
          npm install
          node index.js

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date -d '-1 days' +'%Y-%m-%d')"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.date.outputs.date }}"
          prerelease: false
          title: "${{ steps.date.outputs.date }}"
          files: |
            out/*

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Latest (${{ steps.date.outputs.date }})"
          files: |
            out/*
            
      - name: Copy readme to Pages
        id: copy-readme
        run: cp ./README.md ./out/index.md
            
      - name: Setup Pages
        uses: actions/configure-pages@v1
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: 'out/'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main            
