name: Build

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Run script
        run: |
          npm install
          node index.js

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Push latest cloud maps
        run: |
          git config --global user.name "Matt Eason"
          git config --global user.email "github@matteason.co.uk"
        
          git add . 
          
          git git diff-index --quiet HEAD || commit -m "Add cloud maps for ${{ steps.date.outputs.date }}"
          git push          

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.date.outputs.date }}"
          prerelease: false
          title: "${{ steps.date.outputs.date }}"
          files: |
            latest/*