name: Build

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 23 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Run script
        run: |
          npm install
          node index.js

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date -d '-1 days' +'%Y-%m-%d')"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.date.outputs.date }}"
          prerelease: false
          title: "${{ steps.date.outputs.date }}"
          files: |
            out/*

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest (${{ steps.date.outputs.date }})"
          files: |
            out/*